// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyxtbelggineqthfskgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5eHRiZWxnZ2luZXF0aGZza2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODcwNTQsImV4cCI6MjA2NDc2MzA1NH0.MyoeqdxJP_7tpx1QoiVFW4mkboctoIbI6RQjmb7-KxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);